import { Montserrat, Poppins } from "next/font/google";
import "./globals.css";
// import NavBar from "@/components/shared/NavBar";
// import Header from "@/components/shared/Header";

export const montserrat = Montserrat({
  variable: "--font-montserrat",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
})
const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`h-full antialiased`}
    >
      <body className={`${poppins.className} min-h-full flex flex-col `}>
        {/* <Header />
        <NavBar /> */}
        {children}
        </body>
    </html>
  );
}
